apiVersion: v1
kind: Service
metadata:
  name: my-simple-app-service
spec:
  type: NodePort # Dùng NodePort/LoadBalancer để test
  selector:
    app: my-simple-app
  ports:
    - port: 80
      targetPort: 80
